CREATE SCHEMA if not exists posts;

CREATE TABLE if not exists  posts.posts
(
   id   bigint generated by default as identity
       constraint pk_posts
           primary key,
   title text not null,
    main_text text not null,
    image text,
    likesCount int not null default 0
);


create table if not exists  posts.tags
(
    id   bigint generated by default as identity
        constraint pk_tags
            primary key,
    tag_value varchar(150) not null unique
);
create unique index if not exists  ux_tags_name on posts.tags (lower(tag_value));

create table if not exists  posts.post_tags
(
    post_id bigint not null
        constraint fk_post_tags_post_id
            references posts.posts
            on delete cascade,
    tag_id  bigint not null
        constraint fk_post_tags_tag_id
            references posts.tags
            on delete cascade,
    constraint pk_post_tags
        primary key (post_id, tag_id)
);
create index if not exists ix_post_tags_tag_id on posts.post_tags(tag_id);



create table if not exists posts.comments
(
    id                        bigint generated by default as identity
        constraint pk_comments
            primary key,
    post_id bigint not null
        constraint fk_comments_posts_post_id
            references posts.posts
            on delete cascade,
    text text not null
);

create index if not exists ix_comments_post_id on posts.comments(post_id);
