-- liquibase formatted sql

-- changeset valentin:1772512789383-1
CREATE TABLE market.product
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    guid_id     UUID                                    NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    title       VARCHAR(255)                            NOT NULL,
    description VARCHAR(255),
    img_path    VARCHAR(255),
    price       BIGINT                                  NOT NULL,
    count       INTEGER                                 NOT NULL,
    CONSTRAINT pk_product PRIMARY KEY (id)
);

-- changeset valentin:1772512789383-2
CREATE INDEX ix_product_guid_id ON market.product (guid_id);

